---
abstract: 'Wrapper em torno da API do Buscape'
author:
  - 'Blabos de Blebe <blabos@cpan.org>'
build_requires:
  JSON: 2.53
  List::Util: 1.21
  Test::Most: 0.31
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Buscape-API
requires:
  Carp: 1.26
  Const::Fast: 0.013
  LWP::UserAgent: 6.05
  Moo: 1.003001
  URI: 1.60
resources:
  bugtracker: https://github.com/EstanteVirtual/Buscape-API/issues
  repository: https://github.com/EstanteVirtual/Buscape-API
version: 0.000003
